app.js
config/passport.js
controllers/user-controller.js
middleware/error-handler.js
package.json
routes/index.js
routes/modules/admin.js
routes/modules/user.js

需要注意的部分如下:
signin 路由我統一由單一 controller 函式來做處理，判斷條件是使用 req.originalUrl 來判斷是否可以接受一般使用者登入，或是接受管理員來做登入。
signup 路由裡面，我會檢查幾項:
1. 每個欄位都要填寫
2. name 不能超過 50 字
3. 密碼欄位需要一致
4. account 已經重複註冊
5. email 已經重複註冊

Feat/add signup and signin routes (新增 註冊/登入 路由)

---

app.js
controllers/admin-controller.js
middleware/auth.js
package-lock.json
package.json
routes/modules/admin.js

最後直接改用安裝 cors 套件，直接解決問題，
也有重新跑過測試檔案，沒有問題。

Fix/solve cors issue (解決 CORS 問題)

---

.vscode/settings.json
controllers/user-controller.js
routes/modules/user.js

測試通過 GET /api/users/getUser  以及 POST /api/users/getTweetsOfUser 的 unit tests。
變數命名問題 : 直接將功能回傳值命名為 responseData

Feat/add users basic routes  (新增 GET /api/users/getUser 以及 getTweetsOfUser )

---

controllers/tweet-controller.js
routes/modules/tweet.js

新增路由以下，並且已經通過測試:
GET /api/tweets/:TweetId/replies
POST /api/tweets/:TweetId/replies

Feat/add tweets replies routes (新增有關推文回覆的路由)

---

controllers/admin-controller.js
controllers/tweet-controller.js

主要修正的範圍:
tweetController
adminController
這次修正主要內容:
1. get /api/admin/tweets 增加作者資訊 (tweetedUser)
2. delete /api/admin/tweets/:TweetId 應該會連動 作者的totalTweets, totalLiked 總數、移除底下所有 replies、移除底下所有跟這筆tweet有關的 like 資料
3. post /api/tweet/:TweetId/like 應該會連動 推文者的totalLiked 總數 + 1，以及推文本身的 totalLikes 總數 + 1
4. post /api/tweet/:TweetId/unlike 應該會連動 推文者的totalLiked 總數 - 1，以及推文本身的 totalLikes 總數 - 1
5. 回傳資訊如果有攜帶 user 資料，一律移除密碼欄位
6. 大量操作 DB record 移除的地方，比如 "移除底下所有 replies"，避免 N + 1 的方式透過迴圈來創造過多的 SQL queries，取而代之是使用 SQL "IN" 的語法只用一筆 query 刪掉所有資料。

Fix/solve relational db op issues (新增逆正規化相關欄位處理)

---

controllers/user-controller.js
routes/modules/user.js

本地測試 PUT /api/users/:UserId unit test 通過。
通過 測試:
1.使用者能編輯自己的 account、name、email 和 password
2.編輯時，account 和 email 不能與其他人重覆，若有重覆會跳出錯誤提示
3.使用者能編輯自己的暱稱、自我介紹、個人頭像與封面
錯誤檢查:
1. password 與 checkPassword 是否相同 > 「」
2. account 與 email 是否與其他使用者重複 > 「account 已重覆！」或「email 已重覆！」
3. introduction 上限160字、name 上限50字 > 「字數超出上限！」

Feat/add users edit routes ( 新增 PUT /api/users/:UserId router )

---

controllers/admin-controller.js
controllers/followship-controller.js
controllers/tweet-controller.js
routes/index.js
routes/modules/followship.js

通過測試，另外調整 admin-controller 以及 tweet-controller 直接在 SQL query 裡面就先排掉 password 欄位。

Feat/add followships routes (新增跟隨相關路由)

---

controllers/followship-controller.js
controllers/tweet-controller.js
controllers/user-controller.js
models/user.js
routes/modules/user.js

針對現有以下路由，加入簡易的判斷式:
1. POST /api/followships
2. DELETE /api/followships/:followingId
3. POST /api/tweets/:TweetId/like
4. POST /api/tweets/:TweetId/unlike
有重複跑過測試，不影響單元測試。

Fix/solve self like or follow issues (修正自己喜歡自己的貼文，以及自己追蹤自己的問題)

---

controllers/user-controller.js
models/followship.js
routes/modules/user.js

已通過全部單元測試且功能正常，postman 測試正常。
測試檔預期回傳的格式應是以 : followship 去 include User 資料。
因應我們回傳格式的風格，故採取 User 多對多 User 方式取得資料。
最後 回傳資料中皆有帶入 isFollowed，便於前端判斷是否追隨中。

Feat/add users follow routes ( 新增 GET /api/users/:UserId/followers & followings )

---

controllers/user-controller.js
seeders/20220222020941-users-seed-file.js

處理範圍:
user-controller.js
20220222020941-users-seed-file.js
處理內容:
1. 修正 user controller 裡面 topUsers 沒有反傳 isFollowed 這個 key property
2. 調整 user seed file 裡面 '生成一般使用者數量的變數' 從 5 調整成 15，來讓前端測試首頁側邊欄位時，可以有更多使用者顯示於畫面
已經執行測試檔案，沒有影響其他功能

Fix/solve top users and seed issues (處理 topUsers 函式 以及 種子資料)

---

README.md

doc: add README.md and fill it with rough content (新增 README.md 初稿)

---

controllers/user-controller.js
routes/modules/user.js

feat: add get /api/users/self route and function ( 新增 GET api/usrs/self 取得自己資料 )

---

controllers/tweet-controller.js
controllers/user-controller.js

處理範圍:
user-controller.js/getTopUsers
tweet-controller.js/getTweets
tweet-controller.js/getReplies
處理內容:
針對 getTopUsers 去掉自己本身資料
針對 getTweets 以及 getReplies 修改處理邏輯，如果沒有查詢到任何結果就直接回傳空的陣列
已經執行測試檔案，沒有影響核心功能

Fix/solve top users and seed issues (處理 getTopUsers 去掉自己本身資料)

---

controllers/user-controller.js

調整 likes route 物件名稱 : Tweet > likedTweet
測試通過，不影響程式運作。

fix: adjust key Tweet to likedTweet for likes route ( Likes 物件名稱調整 )

---

README.md

如題，有重新執行測試檔案，沒有影響任何核心功能。
如果 README.md 你這邊有需要補充說明，或是內容修改，我們可以直接討論~~

doc: overhaul almost whole content in README.md (調整 README 內容)

---

README.md
controllers/admin-controller.js

修改範圍:
admin-controller.js/getTweets
admin-controller.js/getUsers
已經執行測試檔案，沒有影響核心功能

Fix/remove empty array issue (移除空陣列報錯的問題)

---

_helpers.js
controllers/user-controller.js

調整錯誤判斷，移動至 imgur helpers。
調整使用者判斷，移動至 edit route 最上面

refactor: move imgur uploading error to helpers ( 將錯誤判斷移至 imgur helpers )

---

.travis.yml
_helpers.js
controllers/user-controller.js

在 travis.yml 加入 JWT_SECRET for pull request AC master

Fix/add env variable travis ( 加入 JWT_SECRET )

---

.travis.yml
_helpers.js
controllers/user-controller.js

本地測試通過，postman測試通過。
新增項目：
在 likes route 加入 tweetedUser

Fix/add tweeted user at likes route ( 在 likes route 加入 tweetedUser )

---

controllers/admin-controller.js
controllers/followship-controller.js
controllers/tweet-controller.js
seeders/20220222020941-users-seed-file.js

新增 lock 機制，讓 transcation 過程鎖住資料列 (table row)，
另外調整 user seed data，修改 introduction 字數數量。
已經重新執行測試檔案，目前不影響核心功能。

Fix/db concurrent op issue (新增 transcation lock 機制)

---

seeders/20220222020941-users-seed-file.js
seeders/20220222023551-tweets-seed-file.js
seeders/20220222050948-replies-seed-file.js

處理範圍:
20220222020941-users-seed-file.js
20220222023551-tweets-seed-file.js
20220222050948-replies-seed-file.js
處理內容:
針對 user.introduction、tweet.description、reply.comment 都使用 faker.lorem.sentence() 來處理種子資料生產的字數過多問題。
已執行測試檔案，不影響核心功能

fix: replace faker.lorem.text with faker.lorem.sentence (調整 seed data 生產字數過多問題)

---

migrations/20190115071420-create-tweet.js
migrations/20190115071421-create-user.js

調整範圍:
20190115071421-create-user.js
20190115071420-create-tweet.js
調整內容:
更改部分欄位從 Sequelize.INTEGER => Sequelize.INTEGER.UNSIGNED，避免欄位出現負數現象。
已執行過測試檔案，目前沒有任何問題

fix: add INTEGER.UNSIGNED to total counts collumns in DB (調整 DB 欄位屬性，增加 UNSIGNED)

---

controllers/user-controller.js

Fix/add password hash at users route ( 新增使用者帳戶密碼雜湊功能 )

---

controllers/user-controller.js

fix: add email error check ( 補上 email check )

---

seeders/20220222023551-tweets-seed-file.js
seeders/20220302141023-followships-seed-file.js
seeders/20220302153110-likes-seed-file.js

新增 followship 以及 likes 種子檔案，另外調整 tweet 的 createdAt 使用 faker 隨機變數
已執行過測試檔案，沒有影響核心功能。

Feat/add followships and likes seeds (緊急新增 followships 以及 likes 種子資料)

---

migrations/20190115071420-create-tweet.js
migrations/20190115071421-create-user.js

修改 tweet 以及 user migration files 裡面的 INTEGER.UNSIGNED 改成 INTEGER。
不然 Travis CI 測試會出現問題。

fix: remove INTEGER.UNSIGNED from total counts (緊急修復: 調整資料類型)

---

controllers/user-controller.js

fix: solve tweets of user order issue ( 調整 個人頁面中所有推文 排序問題 )

---

README.md

除了一般使用者的種子資料從提供兩個，到現在改成提供五個
另外微調其他項目內容

Doc/adjust readme (第四次調整 README.md)
